spring:
  application:
    name: comp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/compkey?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: leo
    password: lou..200499
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379
      password: #没有密码的话不用填
      timeout: 10000
      database: 1

# 设置mybatis寻找对应.xml文件的位置
mybatis:
  type-aliases-package: com.example.comp.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.example.comp.mapper.type
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9031


resource:
  word-graph:
    node: /node/node.csv

# OpenAI
openai:
  api-url: https://api.openai-proxy.org/v1
  api-key: sk-KsQLqgB36Ubu3ybDkYSpwhb8cp8b6PbsDkN9U22Saf5nYnMJ


data:
  neo4j:
    uri: bolt://localhost:7687
    username: leo
    password: lou..200499
    db-name: compword

container:
  redis:
    reco-words:
      list-prefix: comp:reco-word:list
      lru-zset: comp:reco-word:lru
      max-capacity: 5000


async:
  thread-pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 1000
    keep-alive-seconds: 60
    thread-name-prefix: async-service-
    await-termination-seconds: 30
